<?
pll_register_string('custom-1', 'Давайте поговорим', 'custom');
pll_register_string('custom-2', 'Прикрепить файл', 'custom');
pll_register_string('custom-3', 'Отправить заявку', 'custom');
pll_register_string('custom-4', 'Коммерческое предложение', 'custom');
pll_register_string('custom-5', 'У вас есть проект для нас?', 'custom');
pll_register_string('custom-6', 'Республика Беларусь', 'custom');
pll_register_string('custom-7', 'Посмотреть на карте', 'custom');
pll_register_string('custom-8', 'Назад', 'custom');
pll_register_string('custom-9', 'Блогг', 'custom');
pll_register_string('custom-10', 'О нас', 'custom');
pll_register_string('custom-11', 'Как мы работаем', 'custom');
pll_register_string('custom-12', 'Вакансии', 'custom');
pll_register_string('custom-13', 'Награды', 'custom');
pll_register_string('custom-14', 'Отзывы', 'custom');
pll_register_string('custom-15', 'Клиенты', 'custom');
pll_register_string('custom-16', 'Все награды', 'custom');
pll_register_string('custom-17', 'Лидеры в рейтингах', 'custom');
pll_register_string('custom-18', 'Все клиенты', 'custom');
pll_register_string('custom-19', 'Команда', 'custom');
pll_register_string('custom-20', 'Технологии', 'custom');
pll_register_string('custom-21', 'Посмотреть отзыв', 'custom');
pll_register_string('custom-22', 'Оценить проект', 'custom');
pll_register_string('custom-23', 'Узнать цену и сроки', 'custom');
pll_register_string('custom-24', 'Самые популярные теги', 'custom');
pll_register_string('custom-25', 'Тип проекта', 'custom');
pll_register_string('custom-26', 'Сфера', 'custom');
pll_register_string('custom-27', 'Фильтр', 'custom');
pll_register_string('custom-28', 'Все', 'custom');
pll_register_string('custom-29', 'Топ', 'custom');
pll_register_string('custom-30', 'Наше портфолио', 'custom');
pll_register_string('custom-31', 'Остальные проекты', 'custom');
pll_register_string('custom-32', 'Решение', 'custom');
pll_register_string('custom-33', 'Задача', 'custom');
pll_register_string('custom-34', 'Следующий проект', 'custom');
pll_register_string('custom-35', 'Предыдущий проект', 'custom');
pll_register_string('custom-36', 'Этап', 'custom');
pll_register_string('custom-37', 'Средняя стоимость', 'custom');
pll_register_string('custom-38', 'Адрес', 'custom');
pll_register_string('custom-39', 'г. Минск, ул. Лазо 16, 3 этаж, офис 44', 'custom');
pll_register_string('custom-40', 'Блог', 'custom');